.github/workflows/build.yml

- I created a new dedicated user in Redshift + Snowflake and dedicated service account in BigQuery
- I've updated the corresponding secrets
- Currently running integration tests locally with the new credentials to double-check

Update db users

---

.gitignore
scripts/release-pypath/builder/native.py
scripts/release-pypath/builder/virtualenvs.py

resolves #6 
This upgrades deps listed in `CORE_VENV_DEPS` to latest when creating a virtualenv.

Upgrade pip when creating virtualenv

---

scripts/release-pypath/builder/common.py
scripts/release-pypath/builder/homebrew.py

resolves #2 
- set the default Homebrew formula if the release is the latest and greatest non-prerelease

Set the default Homebrew formula

---

scripts/release-pypath/builder/homebrew.py

This is a fix for installing dbt>0.19.0 via homebrew. ([build error](https://github.com/fishtown-analytics/dbt-release/runs/2098367664?check_suite_focus=true#step:12:347))
- upgrades pip prior to install python dependencies from source
- adds back patch to install SCP and grpcio
I tested this locally by:
- updating the 0.19.0 formula to use the new `cryptography` version
- confirmed installation error
- added fix to upgrade pip in the Homebrew formula
- reinstall and confirmed successful installation

upgrade pip and add back patch for installing SCP and grpcio

---

releases/0.21/0.21.rc1.txt

Release 0.21.0rc1

---

releases/0.21/0.21.rc2.txt

Release 0.21.0rc2

---

.github/workflows/_github-release.yml

**Descriptions**:
This pr introduces PoC for the GitHub Release workflow.
_Link to original PR_:
- dbt-labs/actions/pull/19
**Area**:
- CI/CD

[PoC] Add `GitHub Release` workflow to repo

---

.github/workflows/build.yml

We need to update the current Build workflow implementation to test it.
_Changelog_:
- (**Temporary**) Added inputs to be able to skip some steps of the flow;
- (**Temporary**) Updated stages definition to run even when the previous stage skipped;
- Formated code;
- Applied changes were previously made to build, test-build stage in other repos;
- Bumped version for several GH actions to resolve warnings;

[Build] Make workflow flexible for testing

---

.github/workflows/build.yml
.github/workflows/github-release.yml

We need to polish the workflow code to make it production ready.
**Changelog**:
- Updated workflow documentation to match implementation;
- Formated workflow code according to [guidelines](https://github.com/dbt-labs/dbt-core/blob/main/.github/_README.md); 
- Updated notifications messages to use [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions) so that useful information will pop up on the workflow's annotation block;
- Bumped version for some GH actions to resolve warnings;
- Removed inputs that are used for testing;
- Renamed some steps/variables to make more sense;
- Other minor improvements;
**Work results**:
- https://github.com/dbt-labs/dbt-core-release-test/actions/runs/3704304875

[Build] Polish workflow code

---

.github/workflows/build.yml

This PR adds a missing condition for the `[Notification] Upload Artifact From S3 To GitHub` step.

[Build] Add missing step condition 

---

.github/workflows/release-prep.yml

This pull request update commands in the Release Preparation workflow to match the [Version Bump](https://github.com/dbt-labs/actions/blob/main/.github/workflows/version-bump.yml) workflow.
_Changelog_:
- Use more up-to-date commands from `version-bump.yml` workflow;
- Replace `::set-output` commands;
- Format code;
- Update Bash scripts.

[Release Preparation] Update workflow

---

.github/workflows/release-prep.yml

We need to polish the workflow code to make it production ready.
**Changelog**:
- Updated workflow documentation to match implementation;
- Formated workflow code according to [guidelines](https://github.com/dbt-labs/dbt-core/blob/main/.github/_README.md); 
- Updated notifications messages to use [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions) so that useful information will pop up on the workflow's annotation block;
- Renamed some steps/variables to make more sense;
- Other minor improvements;

[Release Preparation] Clean up workflow 

---

.github/workflows/build.yml
.github/workflows/release-prep.yml

**Description**
This pr provides the following improvements:
- Added additional steps to respect the `dbt-spark` configuration;
- Enabled `run-integration-tests` stage;
_Changelog_:
- Added `env_setup_script_path` input;
- Updated `run-integration-tests` stage to respect `env_setup_script_path` input;
- Updated docs;
- Updated `Release Preparation` and `Build` stages to respect `dbt-spark` repo;/
- Fix code format;

[Release] Improve release workflow

---

.github/workflows/pypi-release.yml

We need to uncomment the workflow code to test and improve it.
_Changelog_:
- Uncomment workflow code;
- Rename `testing` to `test_run`;
- Add the `Sanitize Package Name` step for testing against `release-test` repos;
- Switch ref for `dbt-labs/actions/py-package-info` action to test new functionality;
- Rework conditions for stages;
**Ralted PR**:
- dbt-labs/actions/pull/58

[PyPi Release] Update workflow

---

.github/workflows/pypi-release.yml

We need to polish the workflow code to make it production ready.
**Changelog**:
- Updated workflow documentation to match implementation;
- Formated workflow code according to [guidelines](https://github.com/dbt-labs/dbt-core/blob/main/.github/_README.md); 
- Updated notifications messages to use [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions) so that useful information will pop up on the workflow's annotation block;
- Renamed some steps/variables to make more sense;
- Other minor improvements;

[PyPi Release] Clean up workflow

---

.github/workflows/build.yml
.github/workflows/github-release.yml
.github/workflows/release-prep.yml
.github/workflows/slack-post-notification.yml

Polish reusable workflows code.
**Changelog**:
_.github/workflows/slack-post-notification.yml_:
- Add `status` input;
- Change the default value for the `notify_when` input;
- Add workflow notification;
- Add docs;
_.github/workflows/build.yml_:
_.github/workflows/github-release.yml_:
_.github/workflows/release-prep.yml_:
- Code format fix;
- Switch `parse-semver` ref to use the latest changes;
- Other minor fixes;

[Release] Finalize changes

---

.github/workflows/build.yml
.github/workflows/github-release.yml
.github/workflows/pypi-release.yml
.github/workflows/release-prep.yml
.github/workflows/slack-post-notification.yml

This pull request provides updates for the following workflows:
- Version Bump and Changelog Generation;
- Build;
- GitHub Release;
- PyPI Release;
- Post Slack Notification;
**Changelog**:
_Version Bump and Changelog Generation_:
- Code format fix;
- Switch `parse-semver` ref to use the latest changes;
- Other minor fixes;
_Build_:
- Code format fix;
- Switch `parse-semver` ref to use the latest changes;
- Other minor fixes;
_GitHub Release_:
- Code format fix;
_PyPI Release_:
- Uncomment workflow code;
- Rename `testing` to `test_run`;
- Add the `Sanitize Package Name` step for testing against `release-test` repos;
- Switch ref for `dbt-labs/actions/py-package-info` action to test new functionality;
- Rework conditions for stages;
- Update workflow documentation to …

[Release] Cumulative update

---

.github/workflows/release-prep.yml

Add the missing `$` sign before the expression.

[Release Preparation] Fix bash script

---

.github/workflows/README.md
README.md

We need to add general information about the repo.

[Misc] Update README.md

---

.github/workflows/release-prep.yml

When generating the changelog generate the Core Group list off the members of the GitHub Team: Core.

utilize github team membership

---

.github/workflows/release-prep.yml

Added conditional merge step and notification of if anything was merged.

add branch conditional

---

.github/workflows/release-prep.yml

logging more inputs

---

.github/workflows/release-prep.yml

logging more inputs and evaluations

---

.github/workflows/release-prep.yml

removed evaluation from conditional

---

.github/workflows/release-prep.yml

Updated team name here
https://github.com/orgs/dbt-labs/teams/core-group

Update core group name in changie

---

.github/workflows/release-prep.yml

Install `editable-requirements.txt` if file exists

---

.github/workflows/internal-archive-release.yml

resolves 110 in the epic.
Add the guts needed to make third party builds work. I needed to add flexibility for cases like
* adding or omitting static type tags in version file
* external repos
This PR also integrates feedback from #106 that was left hanging:
* Bash ergonomics
* no double setup of python (need to test once I can)
Proof these changes did not break existing builds:
* PG https://github.com/dbt-labs/dbt-postgres/actions/runs/8514355484
* RS https://github.com/dbt-labs/dbt-redshift/actions/runs/8514426366
* BQ https://github.com/dbt-labs/dbt-bigquery/actions/runs/8514385816
* Snow https://github.com/dbt-labs/dbt-snowflake/actions/runs/8514414264
* Spark https://github.com/dbt-labs/dbt-spark/actions/runs/8514458077
* DB …

Add maintainer workflow friendly adjustments

---

.github/workflows/internal-archive-release.yml

I tested this edit on my local machine and successfully removed the line.

Remove core requirements for internal adapter release

---

.github/workflows/internal-archive-release.yml

Update integration-tests `dbt_core_branch` arg in internal-archive-release.yml

---

.github/workflows/slack-post-notification.yml

This [workflow](https://github.com/dbt-labs/dbt-mantle/actions/runs/11009660776/job/30569826631) is failing because of special characters.  Add quotes so we treat it correctly.

add quotes to ensure shell interprets it correctly

---

.github/workflows/internal-archive-release.yml

update HATCH_ADAPTERS list

---

.github/workflows/build.yml

resolves #111
Leaves in the input so all the workflows don't need to be modified to stop passing it in but no longer uploads anything to AWS.

pull AWS upload
