- scripts/release-pypath/builder/homebrew.py
This is a workaround for installing snowflake connector python for dbt with Homebrew.
SCP installs build-system dependencies [PEP 517](https://www.python.org/dev/peps/pep-0517/) listed [here](https://github.com/snowflakedb/snowflake-connector-python/blob/master/pyproject.toml) for versions >= 2.3.0. Homebrew tries to install the build dependencies from source, which fails to install. This can be recreated by running `pip install -v --no-deps --no-binary :all: --ignore-installed snowflake-connector-python==2.3.6`
```
pip._internal.exceptions.InstallationError:
Command errored out with exit status 1: /usr/local/Cellar/dbt/0.19.0b1_1/libexec/bin/python
/usr/local/Cellar/dbt/0.19.0b1_1/libexec/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix …
```
> Add fix for installing snowflake-connector-python

- scripts/release-pypath/builder/homebrew.py
I think it makes sense to manually apply fixes for installing SCP and other deps instead of baking it into the release process. I'm hopeful that newer versions will not need custom code in Homebrew formula to be able to install!
> Remove one off fixes for installing snowflake-connector-python

- releases/0.20/0.20.0rc2.txt
- scripts/release-pypath/builder/homebrew.py
- scripts/release-pypath/builder/native.py
- 0.20.b1 and 0.20.rc1 were released from the `develop` branch but the branch `0.20.latest` was created after those releases, and `develop` has since diverged. This changes the release branch to `0.20.latest`.
- in version 0.20 we renamed dev requirements. Since a patch of 0.19 was last to be released, we have to rename dev requirements for this release.
> 0.20.0rc2 release

- scripts/release-pypath/builder/homebrew.py
adds check to exclude `dbt-extractor` from the list of dbt plugins.
> quickfix to unblock 0.20.0rc2

- .github/workflows/_github-release.yml
**Description**: 
This pr resolves warnings that are related to the usage of`::set-output` command and fixes the path to where to download the build artifact.
Changelog:
- Replaced `::set-output` with `$GITHUB_OUTPUT`;
- Fix the path to where to download the build artifact.
> [GitHub Release] Replace `::set-output` and fix path to download artifact

- .github/workflows/_github-release.yml
We need to polish the workflow code to make it production ready.
**Changelog**:
- Split the `github-release` stage into `publish-github-release` and `create-github-release`;
- Replace the `checkout` task with passing `--repo` argument to GitHub CLI for the `publicize-github-release` and `check-release-exists` stages;
- Add a description to all workflow inputs;
- Rename `testing` input to `test_run`;
- Format workflow according to [guidelines](https://github.com/dbt-labs/dbt-core/blob/main/.github/_README.md);
- Updated notifications messages to use [workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions) so that useful information will pop up on the workflow's annotation block.
**Work results**:
- Build and push draft …
> [GitHub Release] Polish workflow code

- .github/workflows/release-prep.yml
We need to rework the `run-tests` stage and provide the ability to launch test runs.
_Test run behavior_:
- Temp branch naming pattern: `prep-release/test-run/${{ inputs.version_number }}_$GITHUB_RUN_ID`
- Changes from the temp branch will not be merged into the target branch;
- Temp branch will not be removed automatically;
- Final SHA will be set to commit SHA from temp branch;
_Changes in default behavior_:
- The temp branch will be removed when changes are merged to the target branch;
**Changelog**:
_Launch test run_:
- Add `test-run` input to launch test run;
- Update branch name generation script to to respect `test-run` input;
- Update `merge-for-release` stage definition to respect `test-run` input;
- Update `get-release-sha` stage definition to respect `test-run` …
> [Release Preparation] Improve workflow

- .github/workflows/slack-post-notification.yml
This pr introduces a `Slack notification` workflow.
_Workflow description_:
- The `notify-slack-action` action is wrapped into a reusable workflow so that we can reuse it in other workflows;
- The `notify_when` input controls when we push notifications to the Slack channel (_By default_: notify when workflows fail);
- The `notification_title` input will change the message title in the notification (_By default_: Release Process Status);
_Changelog_:
- Added `.github/workflows/slack-post-notification.yml`
> [Slack notification] Introduce workflow

- .github/workflows/build.yml
- .github/workflows/github-release.yml
- .github/workflows/pypi-release.yml
- .github/workflows/release-prep.yml
Improve and update reusable workflows.
**Changelog**:
_Version Bump and Changelog Generation workflow_:
- Added `nightly_release` input;
- Update workflow to respect `nightly_release` input;
- Added `Setup Environment Variables - Secrets Context` step to setup secrets for integration tests;
_Build workflow_:
- Added `nightly_release` input;
- Update workflow to respect `nightly_release` input;
_GitHub Release workflow_:
- Change the type for the `test_run` input to avoid typecast to string;
- Fix the `publish-draft-release` stage condition to respect the `test_run` input type;
_PyPI release workflow_:
- Change the type for the `test_run` input to avoid typecast to string;
- Fix the `Set Version Existence For Subsequent Jobs` step to compare the normalized version with the …
> [Release] Improve and fix reusable workflows

- .github/workflows/release-prep.yml
Tweak several conditions for the Release Preparation workflow.
**Changelog**:
_`merge-changes-into-target-branch`_:
- changed `if` condition from `${{ inputs.test_run == false }}` to `${{ inputs.test_run == false && !failure() && !cancelled() }}`;
_`determine-release-sha`_:
- changed `if` condition from `always()` to `${{ !failure() && !cancelled() }}`;
> [Release Preparation] Fix workflow

- .github/workflows/release-prep.yml
We need to update the `Generate Release Changelog` script to respect the case when we release a patch without prerelease. In this case, we don't have a folder with a changelog, and this line cause failure:
https://github.com/dbt-labs/dbt-release/blob/d31e54238f04d86b5db7f22aec20aaeda52060fa/.github/workflows/release-prep.yml#L310
To avoid such an issue, we need to check if that related folder exists and, if not, doesn't include it.
_Changelog_:
- `Generate Release Changelog` script updated to check that folder `./changes/<base_version>` exists before running the `changie batch` command;
> [Release Preparation]  Update `Generate Release Changelog` script

- .github/workflows/release-prep.yml
The version bump step is leaving white space. To resolve this, we need to reorg steps that remove trailing whitespaces and extra newlines to execute them after the version bump is completed and before the changes are committed.
**Changelog**:
- Reorg steps in the workflow
**Related issue**:
- #54
> [Release Preparation] Reorg steps in workflow

- .github/workflows/build.yml
- .github/workflows/release-prep.yml
In the current workflow implementation, we have specific steps for different repos. Currently, repo names are hardcoded with a `release-test` postfix. As a result, related steps are skipped when we try to run these workflows against prod repos. This pr replaces the equality operator with the `contains` expression so that workflow will work fine against both prod and release-test repos.
**Changelog**:
`build.yml`:
- Replace the equality operator with the `contains` expression
`release-prep.yml`:
- Replace the equality operator with the `contains` expression
**Related issue**:
- #53
> [Release] Rework repo name check

- .github/workflows/pypi-release.yml
We need to increase retries attempts to make sure that the package index will have enough time to propagate info about the new package version.
**Changelog**:
- Retries bumped up: 4 -> 8
> [PyPi Release] Increase retries for `py-package-info` action

- .github/workflows/release-prep.yml
Part of https://github.com/dbt-labs/dbt-core/issues/6906
Uses the base-version for the changelog to ensure we don't capture the `*.dev<date>` portion in release test versions.  The alternative is a lot more overly complex logic to account for the `*.dev<date>` portion of the version.
Pre releases are handles in the first part of the if statement.
> update changelog path

- .github/workflows/release-prep.yml
Because spark is still on CirclCI we need to run version_bump.yml separately still.  This ensures we fail out if the version doesn't match and/or the changelog still need to be generated.
> add logic for spark safety

- .github/workflows/github-release.yml
- .github/workflows/pypi-release.yml
- .github/workflows/release-prep.yml
Description
Update versions of used Github Actions ahead of:
[node12 deprecation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) (Summer 2023)
[set-output deprecation](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) fully disabled on 31st May 2023)
> update used gh actions ahead of set-output, node12 deprecation

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/implementation-ticket.yml
- .github/ISSUE_TEMPLATE/regression-report.yml
- .github/pull_request_template.md
- CONTRIBUTING.md
- LICENSE
- README.md
resolves https://github.com/dbt-labs/dbt-core/issues/9221
This repository already contained the `README.md` but it was a non standard format.  It also already had dependabot set up.
I added the  `CONTRIBUTING.md`, issue and pr templates, modified the `README.md` for format, and added an apache 2 license.
> OSS Standardization

- .github/workflows/pypi-release.yml
We need to use the latest versions of parse-semver and py-package-info from the actions repo. Instead of creating a new version, we have chosen to let the references track main instead.
> Unpin uses of parse-semver and py-package-info from actions v1.1.0

- .github/workflows/internal-archive-release.yml
resolves 38 in the epic
Finish this up for 1p repos.
- Better docs throughout
- Use env vars to minimize string literals
- Code this in such a way that we only have to edit one literal when moving more adapters over the hatch
- Add conditional testing for different adapters
> Finish internal build pipeline reusable workflow

- .github/workflows/release-docker.yml
resolves #109 
Move docker release workflow here instead of in dbt-core since we all share it.
> add docker release

- .github/actions/latest-wrangler/Dockerfile
- .github/actions/latest-wrangler/README.md
- .github/actions/latest-wrangler/action.yml
- .github/actions/latest-wrangler/examples/example_workflow.yml
- .github/actions/latest-wrangler/examples/example_workflow_dispatch.json
- .github/actions/latest-wrangler/main.py
- .github/workflows/release-docker.yml
resolves #
Makes latest-wrangler no longer relative so that it works for manual triggers and workflow triggers in the docker workflow.
> add latest-wrangler

- .github/workflows/release-docker.yml
resolves #
Manual triggers won't work on this workflow since the contect would be in the wrong repo.
Remove the `workflow_dispatch` trigger & move the docker/setup-buildx-action@v3 into the main job.
> remove manual trigger, combine buildx aciton into job

- .github/dependabot.yml
`dependabot` does not allow for multiple directories or recursion. Each directory requires an entry.
> Update dependabot to account for multiple directories

- .github/workflows/release-docker.yml
We're combining two different ways of releasing docker containers. We should consolidate to just using buildx. Additionally, since we have now moved the Dockerfiles into each repo, we do not need to identify the package, only the version to publish.
> Use buildx to identify the platform to release

- .github/actions/latest-wrangler/main.py
- .github/workflows/release-docker.yml
The `latest-wrangler` implementation assumes there are existing releases for a given Docker release. When using this for the new `dbt-postgres` Docker release, it failed because it could not compare the proposed release of `1.8.0` to anything because the published releases was empty.
> Allow for new Docker releases with no previously published releases

- .github/workflows/internal-archive-release.yml
We updated the command to run unit tests in `hatch`-based projects. It needs to be updated here.
> Update hatch command for unit tests

- .github/actions/latest-wrangler/Dockerfile
- .github/workflows/release-docker.yml
Make sure the container for the latest-wrangler action uses a single version of python.  Since this is just getting information and not actually building anything we can be slightly less optimized and just use the single container and drop the distroless one. 
Test run off branch: https://github.com/dbt-labs/dbt-core/actions/runs/11040717641/job/30669366369
> Fix latest-wrangler

- .github/actions/next-cloud-release-version/get_next_release_version.py
Turns out we needed to work out an edge case with the way `post10` is alnum sorted, rather than numerically sorted. I added a helper function to solve this.
Also, I tried adding some simple default logic to avoid crash outs if no prior versions are stored in the repository, which could happen for newly archived adapters.
For testing, I just used the inputs from the actions themselves:
```
python get_next_release_version.py --released_version 1.8.0rc1+build1,1.8.0rc1+build2,1.9.0.post1+e5b28d67cf4b870da81674de3e1b84c4474a00a6,1.9.0.post10+78f86674bc726000686a484c4d2f0e2f9d350ed1,1.9.0.post2+2576a08379e248d393b9a698e58fac0d32c23648,1.9.0.post3+8ae3ec89f7bc829cfa9351100905e13bc42542ac,1.9.0.post4+d51584d606a9b56247f6c950006274c89ab7ab0c,1.9.0.post5+7fb4549abc52d53dfdbf02da423ee58cc8696ccc,1.9 …
```
> Fix duplicate post suffixes for internal archive release

- .github/workflows/internal-archive-release.yml
now that dbt-databricks has moved to pyproject.toml our assumption that adapters have a setup.py no longer holds and we should move to a more setup agnostic command.
> replace setup.py reference with generic `build` call

- .github/workflows/release-prep.yml
ubuntu 20.04 is EOL.  This upgrades the os and also stops using the shared core action to add permissions for testing.
Relates to https://github.com/dbt-labs/dbt-core/pull/11354
Need to test this with adapter releases.
> INC-2124 stop using the core action and upgrade ubuntu

- .github/workflows/release-docker.yml
docker/build-push-action@v5 used ubuntu 20.04.  It's EOL.
> bump docker build action for ubuntu EOL

- .github/workflows/pypi-release.yml
resolves https://github.com/dbt-labs/dbt-core/issues/11422
The newest version of setuptools uses version 2.4 of metadata.  The GHA was failing due to older versions using an older version of twine.  This update gets all the dependencies back in order.
> Fixing release

- .github/workflows/build.yml
You can't pass secrets into workflow when the secret isn't defined.  To prevent breaking changes (old versions of adapters also use this release) define the secrets even though we never use them.
Error in calling workflows
```
[Invalid workflow file: .github/workflows/release.yml#L154](https://github.com/dbt-labs/dbt-core/actions/runs/14221544502/workflow)
The workflow is not valid. .github/workflows/release.yml (Line: 154, Col: 26): Invalid secret, AWS_ACCESS_KEY_ID is not defined in the referenced workflow. .github/workflows/release.yml (Line: 155, Col: 30): Invalid secret, AWS_SECRET_ACCESS_KEY is not defined in the referenced workflow.
```
> add back secret definition
